esphome:
  name: uvr64_dlbus
esp8266:
  board: d1_mini

logger:

external_components:
  - source:
      type: git
      url: https://github.com/DerTolleMaz/esphome-uvr64
      ref: main
    components: [uvr64_dlbus]
    refresh: always

sensor:
  - platform: template
    name: "UVR64 Solarthermie"
    id: temp0
  - platform: template
    name: "UVR64 Solarthermie Boiler"
    id: temp1
  - platform: template
    name: "UVR64 Solarthermie Puffer Unten"
    id: temp2
  - platform: template
    name: "UVR64 Solarthermie Pool Waermetauscher"
    id: temp3
  - platform: template
    name: "UVR64 Heizung Pool Waermetauscher"
    id: temp4
  - platform: template
    name: "UVR64 Solarthermie Puffer Oben"
    id: temp5

binary_sensor:
  - platform: template
    name: "UVR64 Relay Boiler"
    id: relay0
  - platform: template
    name: "UVR64 Relay Puffer"
    id: relay1
  - platform: template
    name: "UVR64 Relay Solarthermie Pool Waermetauscher"
    id: relay2
  - platform: template
    name: "UVR64 Relay Heizung Pool Waermetauscher"
    id: relay3

# DL-Bus-Komponente
uvr64_dlbus:
  id: uvr
  pin: D2
  temp_sensors:
    - temp0
    - temp1
    - temp2
    - temp3
    - temp4
    - temp5
  relay_sensors:
    - relay0
    - relay1
    - relay2
    - relay3

