# Example configuration for the UVR64 DL-Bus component

uart:
  id: dl_uart
  rx_pin: RX
  baud_rate: 2400

external_components:
  - source:
      type: git
      url: https://github.com/DerTolleMaz/esphome-uvr64
    components: [uvr64_dlbus]
logger:
  level: DEBUG
  baud_rate: 0

sensor:
  - platform: uvr64_dlbus
    uart_id: dl_uart
    decode_xor: true
    temperatures:
      - name: "UVR64 Temp 1"
      - name: "UVR64 Temp 2"
      - name: "UVR64 Temp 3"
      - name: "UVR64 Temp 4"
      - name: "UVR64 Temp 5"
      - name: "UVR64 Temp 6"
    relays:
      - name: "UVR64 Relay 1"
      - name: "UVR64 Relay 2"
      - name: "UVR64 Relay 3"
      - name: "UVR64 Relay 4"
